### ISSUE TITLE
[2016]增加 Support US 

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/rubyconf.tw#40]
在現在的頁面上增加 Support US[EN,CH]
EN 連到：http://rubyconf.tw/2016/rubyconftw2016-cfs-en.pdf
CH：http://rubyconf.tw/2016/rubyconftw2016-cfs-cht.pdf

**Comment by irene84111** [comment]
DONE：https://github.com/rubytaiwan/rubyconf.tw/pull/41
預設 Support Us 為英文文件，令括號中文文件
